services:
    laravel.test:
        container_name: letterly-laravel
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
        image: sail-8.2/app
        ports:
            - "${APP_PORT:-80}:80"
        environment:
            LARAVEL_SAIL: 1
        volumes:
            - ".:/var/www/html"
        networks:
            - sail
        depends_on:
            - mongodb

    mongodb:
        container_name: letterly-mongodb
        image: "mongo:latest"
        ports:
            - "${MONGO_DB_PORT:-27017}:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: "${MONGO_DB_USERNAME}"
            MONGO_INITDB_ROOT_PASSWORD: "${MONGO_DB_PASSWORD}"
            MONGO_INITDB_DATABASE: "${MONGO_DB_DATABASE}"
        volumes:
            - "sail-mongodb:/data/db"
        networks:
            - sail

networks:
    sail:
        driver: bridge

volumes:
    sail-mongodb:
        driver: local
