services:
    laravel.test:
        platform: linux/amd64
        container_name: letterly-laravel
        image: jiran-study:latest
        ports:
            - "${APP_PORT:-80}:80"
        environment:
            LARAVEL_SAIL: 1
        volumes:
            - ".env:/var/www/html/.env"
        networks:
            - sail
        depends_on:
            - mongodb

    mongodb:
        platform: linux/amd64
        container_name: letterly-mongodb
        image: "mongo:latest"
        ports:
            - "${MONGO_DB_PORT:-27017}:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: "${MONGO_DB_USERNAME}"
            MONGO_INITDB_ROOT_PASSWORD: "${MONGO_DB_PASSWORD}"
            MONGO_INITDB_DATABASE: "${MONGO_DB_DATABASE}"
        volumes:
            - "letterly-mongodb:/data/db"
        networks:
            - sail

networks:
    sail:
        driver: bridge

volumes:
    letterly-mongodb:
        driver: local
